### ISSUE TITLE
SLF4J error/warning

### ISSUE THREAD

**Issue by kxygk** [cailuno/denisovan#1]
I've just added `denisovan` to a blank hello world app

``` clojure
(ns test-denisovan.core
  (:require [denisovan.core :as den])
  (:gen-class))

(defn -main
  "I don't do a whole lot ... yet."
  [& args]
  (println "Hello, World!"))
```

and I get this error/warning on output

```
~/USB/Projects/test-denisovan $ lein run
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Hello, World!
```

I'm uncertain if it's a `denisovan` error or it's coming from one of the dependencies

**Comment by whilo** [comment]
I cannot reproduce this. Running `lein deps :tree` on denisovan does not list slf4j and when I create an empty project and insert your code, I do not see the SLF4J messages. I think it is some dependency issue (maybe with your `profiles.clj`)?

**Comment by kxygk** [comment]
I'm pretty fresh with Clojure, so thanks for showing me `lein deps :tree`. That actually pointed out to me that the default `lein` app template was using `[org.clojure/clojure "1.8.0"]` which was causing some version conflict (uncomplicated libs are expecting 1.9.0). Once I version bumped to 1.9.0 the SLF4J error went away :)

I am left with a warning, but it's in `vertigo.core` and that lib looks unmaintained - so I guess there isn't anything to do there

```
geokon@ux303-ubuntu:~/USB/Projects/test-denisovan$ lein run
WARNING: any? already refers to: #'clojure.core/any? in namespace: vertigo.core, being replaced by: #'vertigo.core/any?
Hello, World!
```

Thanks for your help again, and sorry this was a non-issue
